services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: buzon_db
      POSTGRES_USER: buzon_user
      POSTGRES_PASSWORD: buzon_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"   # VNC opcional para ver el navegador
    shm_size: 2gb

  celery:
    build: .
    command: celery -A buzon_electronico_tjaez worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A buzon_electronico_tjaez beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:

  postgres_data:
