version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: buzon_db
      POSTGRES_USER: buzon_user
      POSTGRES_PASSWORD: buzon_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A buzon_electronico_tjaez worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A buzon_electronico_tjaez beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data: