# Generated by Django 5.2.13 on 2026-05-05 00:30

import django.db.models.deletion
import uuid
import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('RAG_INICIAL', 'Expediente RAG Inicial'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('AMPARO', 'Amparo'), ('OTRO', 'Otro')], max_length=50)),
                ('numero_expediente', models.CharField(blank=True, max_length=20, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('ponencia', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_ciudadano', models.EmailField(max_length=254)),
                ('numero_sobres', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('digito_verificador', models.CharField(default=web.models._generar_digito_verificador, max_length=6)),
                ('estado', models.CharField(choices=[('ETIQUETA_GENERADA', 'Etiqueta Generada'), ('DEPOSITADO', 'Depositado'), ('NO_PRESENTADO', 'No Presentado'), ('CANCELADO', 'Cancelado')], default='ETIQUETA_GENERADA', max_length=20)),
                ('fecha_caducidad', models.DateTimeField()),
                ('numero_sobre', models.PositiveIntegerField()),
                ('fecha_deposito', models.DateTimeField(blank=True, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='web.promocion')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['numero_sobre'],
            },
        ),
    ]
