# Generated by Django 5.2.13 on 2026-05-04 22:35

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuzonElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RECIBIDO', 'Recibido'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
            ],
            options={
                'verbose_name': 'Buzón Electrónico',
                'verbose_name_plural': 'Buzones Electrónicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
