# Generated by Django 5.2.13 on 2026-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzonelectronico',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus'),
        ),
    ]
