# Generated by Django 5.2.16 on 2026-07-13 21:46

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzonExpedienteRAGInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Expediente RAG Inicial',
                'verbose_name_plural': 'Buzones - Expediente RAG Inicial',
            },
        ),
    ]
