# Generated by Django 5.2.16 on 2026-07-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_buzonexpedienteraginicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buzonexpedienteraginicial',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='buzonexpedienteraginicial',
            name='numero_expediente',
        ),
        migrations.RemoveField(
            model_name='buzonexpedienteraginicial',
            name='ponencia',
        ),
    ]
