# Generated by Django 5.2.13 on 2026-05-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_buzonelectronico_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzonelectronico',
            name='año_expediente',
            field=models.IntegerField(default=45566, verbose_name='Año del Expediente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buzonelectronico',
            name='numero_expediente',
            field=models.CharField(default=2026, max_length=20, verbose_name='Número de Expediente'),
            preserve_default=False,
        ),
    ]
