# Generated by Django 5.2.13 on 2026-05-04 23:59

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_buzonelectronico_año_expediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzonAlegatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Alegatos',
                'verbose_name_plural': 'Buzones - Alegatos',
            },
        ),
        migrations.CreateModel(
            name='BuzonAmparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Amparo',
                'verbose_name_plural': 'Buzones - Amparo',
            },
        ),
        migrations.CreateModel(
            name='BuzonContestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Contestación',
                'verbose_name_plural': 'Buzones - Contestación',
            },
        ),
        migrations.CreateModel(
            name='BuzonDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
            ],
            options={
                'verbose_name': 'Buzón - Demanda',
                'verbose_name_plural': 'Buzones - Demanda',
            },
        ),
        migrations.CreateModel(
            name='BuzonExpedienteRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Expediente RAG',
                'verbose_name_plural': 'Buzones - Expediente RAG',
            },
        ),
        migrations.CreateModel(
            name='BuzonIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Incidente',
                'verbose_name_plural': 'Buzones - Incidente',
            },
        ),
        migrations.CreateModel(
            name='BuzonInformeAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Informe de Autoridad',
                'verbose_name_plural': 'Buzones - Informe de Autoridad',
            },
        ),
        migrations.CreateModel(
            name='BuzonOtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
                ('especifique', models.CharField(max_length=255, verbose_name='Especifique')),
            ],
            options={
                'verbose_name': 'Buzón - Otros',
                'verbose_name_plural': 'Buzones - Otros',
            },
        ),
        migrations.CreateModel(
            name='BuzonRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(choices=[('DEMANDA', 'Demanda'), ('CONTESTACION', 'Contestación'), ('ALEGATOS', 'Alegatos'), ('INFORME_AUTORIDAD', 'Informe de Autoridad'), ('RECURSO', 'Recurso'), ('INCIDENTE', 'Incidente'), ('AMPARO', 'Amparo'), ('EXPEDIENTE_RAG_INICIAL', 'Expediente de Resp. Admvas (RAG) Inicial'), ('EXPEDIENTE_RAG', 'Expediente de Resp. Admvas (RAG)'), ('OTROS', 'Otros')], max_length=30, verbose_name='Tipo de Promoción')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico para acuse provisional')),
                ('numero_sobres', models.PositiveIntegerField(verbose_name='Número de Sobres')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETRASADO', 'Retrasado')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_recibir', models.DateTimeField(default=web.models.default_fecha_recibir, verbose_name='Fecha para Recibir')),
                ('numero_expediente', models.CharField(max_length=100, verbose_name='Número de Expediente')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('ponencia', models.CharField(choices=[('PONENCIA_1', 'Ponencia 1'), ('PONENCIA_2', 'Ponencia 2'), ('PONENCIA_3', 'Ponencia 3')], max_length=20, verbose_name='Ponencia')),
            ],
            options={
                'verbose_name': 'Buzón - Recurso',
                'verbose_name_plural': 'Buzones - Recurso',
            },
        ),
        migrations.DeleteModel(
            name='BuzonElectronico',
        ),
    ]
